import fs from "fs/promises";
import path from "path";
import { run, runCapture } from "./shell.js";
import { readConfig } from "./config.js";
import { dnsmasqDir } from "./paths.js";
import { removeFileIfExists, writeFileIfChanged, writeFileSudoIfNeeded, readFileContent } from "./file-utils.js";

function normalizeHost(host: string) {
    return host.trim().toLowerCase();
}

function safeFileName(host: string) {
    return host.replace(/[^a-z0-9._-]/gi, "_");
}

function confPathFor(host: string) {
    return path.join(dnsmasqDir(), `${safeFileName(host)}.conf`);
}

function buildDnsmasqConf(host: string, address: string) {
    return ["# generated by harbor", `address=/${host}/${address}`, `listen-address=${address}`].join("\n")
}

export async function addDnsmasqConfig(host: string) {
    host = normalizeHost(host);
    const cfg = readConfig()

    await fs.mkdir(dnsmasqDir(), { recursive: true });

    const filePath = confPathFor(host);
    const content = buildDnsmasqConf(host, cfg.dnsmasq.address);

    await writeFileIfChanged(filePath, content);
}

export async function removeDnsmasqConfig(host: string) {
    host = normalizeHost(host);
    const filePath = confPathFor(host);
    await removeFileIfExists(filePath);
}

export async function implementDnsmasqImport() {
    await fs.mkdir(dnsmasqDir(), { recursive: true });

    const dnsmasqConfPath = await resolveDnsmasqConfPath();
    const current = await readFileContent(dnsmasqConfPath);

    const importLine = `conf-dir=${ensureTrailingSlash(dnsmasqDir())},*.conf`;

    const exists = current
        .split("\n")
        .map((l) => l.trim())
        .some((l) => l === importLine);

    if (exists) return;

    const next = [
        current.trimEnd(),
        "",
        "# harbor",
        importLine,
        "",
    ].join("\n");

    await writeFileSudoIfNeeded(dnsmasqConfPath, next);
}

/**
 * Reload dnsmasq and flush macOS DNS cache so new domains are immediately available.
 */
export async function reloadDnsmasq(): Promise<void> {
    await run('brew', ['services', 'restart', 'dnsmasq'], 'Restarting dnsmasq...', true);
    // Flush macOS DNS cache
    await run('dscacheutil', ['-flushcache'], undefined, true);
    await run('killall', ['-HUP', 'mDNSResponder'], undefined, true);
}

async function resolveDnsmasqConfPath(): Promise<string> {
    const prefix = await runCapture('brew', ['--prefix']);
    return path.join(prefix, 'etc', 'dnsmasq.conf');
}

function ensureTrailingSlash(p: string) {
    return p.endsWith(path.sep) ? p : p + path.sep;
}